server:
  port: 30202

spring:
  application:
    name: demo-kettle
  datasource:
    url: jdbc:mysql://localhost:3306/pipeline_demo?useSSL=false&serverTimezone=UTC
    username: root
    password: adminer
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local

alinesno.data:
  kettle:
    env: development
    kafkaServers: 192.168.101.18:9092
    user-key: aip@local