server:
  port: 30202

spring:
  application:
    name: demo-kettle
  datasource:
    url: jdbc:mysql://localhost:3306/pipeline_demo?useSSL=false&serverTimezone=UTC
    username: root
    password: adminer
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      enable: false
    initialize-schema: always
    jdbc:
      table-prefix: my_batch_
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local